### ISSUE TITLE
Would you accept a PR with the configurable option to select the plain text?

### ISSUE THREAD

**Issue by mjacobus** [Dynge/gitmoji.nvim#1]
Hey! thank you for this awesome plugin.

Would you be willing to accept a PR where setup takes the option to select the plain text `":bug:"` instead of "🐛" ?

![image](https://github.com/Dynge/gitmoji.nvim/assets/226834/77f65589-6e90-4599-b59e-93133204483a)

It may take forever, since I still need to master lua though 😄

**Comment by Dynge** [comment]
Hi @mjacobus. Very glad to hear you like the plugin.

I thought about adding that feature as well. I think it can be accomplished quite easily by adding an extra option or field to items.lua. 

But youre very welcome to share your thoughts on a potential solution.

Thanks a lot.

**Comment by Dynge** [comment]
@mjacobus  I've added the functionality. Please checkout the README to see how to activate the functionality :)

Let me know if theres any trouble with it.
Thanks for the suggestion!

**Comment by mjacobus** [comment]
@Dynge that is so awesome, thank you very much!

It was not very clear to me though, how to set that up. I see by the [code](https://github.com/Dynge/gitmoji.nvim/blob/7e4174a15a8204794141f243324cd56d6d2bbea6/lua/gitmoji/config.lua#L12) I should use `complete_as = text`, but I am not quite sure where to place it. 

Should it be?

```lua
  require("gitmoji").setup({
    completion = {
      complete_as = "text"
    }
  })
```

Or...

```lua
require("cmp").setup({
  sources = {
    { 
      name = 'gitmoji',
      opts = {
....
    }
  })
})
```

**Comment by Dynge** [comment]
> ```lua
>   require("gitmoji").setup({
>     completion = {
>       complete_as = "text"
>     }
>   })
> ```

This should do it. 😃

**Comment by Dynge** [comment]
Thanks for the feedback. Ill update the readme to hopefully make it clearer

**Comment by Dynge** [comment]
Closing the issue - assuming it works for you. 😁

**Comment by mjacobus** [comment]
You assumed correctly. 😄 

Thank you so much 🙇🏻

**Comment by Dynge** [comment]
Thats good to hear!
